# Generated by Django 5.1.7 on 2025-03-19 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=255)),
                ('apellido_paterno', models.CharField(max_length=255)),
                ('apellido_materno', models.CharField(max_length=255)),
                ('correo', models.CharField(max_length=250)),
                ('contrasena', models.CharField(max_length=250)),
                ('telefono', models.BigIntegerField(max_length=10)),
                ('clave', models.CharField(max_length=255, unique=True)),
                ('curp', models.CharField(max_length=255, unique=True)),
                ('sexo', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Facilitador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=255)),
                ('apellido_paterno', models.CharField(max_length=255)),
                ('apellido_materno', models.CharField(max_length=255)),
                ('correo', models.CharField(max_length=250)),
                ('contrasena', models.CharField(max_length=250)),
                ('telefono', models.BigIntegerField(max_length=10)),
                ('clave', models.CharField(max_length=255, unique=True)),
                ('curp', models.CharField(max_length=255, unique=True)),
                ('sexo', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Diplomado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_diplomado', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('grupo', models.CharField(max_length=255)),
                ('facilitador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.facilitador')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.periodo')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_curso', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('grupo', models.CharField(max_length=255)),
                ('facilitador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.facilitador')),
                ('periodo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.periodo')),
            ],
        ),
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_taller', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('grupo', models.CharField(max_length=255)),
                ('facilitador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.facilitador')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.periodo')),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=255)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.alumno')),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.curso')),
                ('diplomado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.diplomado')),
                ('taller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.taller')),
            ],
        ),
    ]
