# Generated by Django 5.1.7 on 2025-03-22 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_curso_cupos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='facilitador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.facilitador'),
        ),
    ]
