# Generated by Django 5.1.7 on 2025-03-31 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0004_alter_curso_facilitador'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
