# Generated by Django 5.1.7 on 2025-04-02 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0005_curso_visible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='visible',
        ),
        migrations.AddField(
            model_name='facilitador',
            name='clave_unica',
            field=models.BigIntegerField(null=True),
        ),
    ]
