# Generated by Django 5.1.7 on 2025-04-02 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0006_remove_curso_visible_facilitador_clave_unica'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facilitador',
            name='clave_unica',
        ),
        migrations.AddField(
            model_name='taller',
            name='cupos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taller',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taller',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
