# Generated by Django 5.1.7 on 2025-04-02 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0007_remove_facilitador_clave_unica_taller_cupos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diplomado',
            name='cupos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diplomado',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diplomado',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
