# Generated by Django 5.1.7 on 2025-04-03 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0008_diplomado_cupos_diplomado_hora_fin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taller',
            name='facilitador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.facilitador'),
        ),
        migrations.AlterField(
            model_name='taller',
            name='periodo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.periodo'),
        ),
    ]
