# Generated by Django 5.1.7 on 2025-04-04 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0009_alter_taller_facilitador_alter_taller_periodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='clave_alumno',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='facilitador',
            name='clave_facilitador',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
