# Generated by Django 5.1.7 on 2025-04-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0010_alumno_clave_alumno_facilitador_clave_facilitador'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='publicado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taller',
            name='publicado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='telefono',
            field=models.BigIntegerField(),
        ),
    ]
