# Generated by Django 5.1.7 on 2025-04-09 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0011_curso_publicado_taller_publicado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='duracion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='modalidad',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='diplomado',
            name='duracion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diplomado',
            name='modalidad',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='taller',
            name='duracion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taller',
            name='modalidad',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
