# Generated by Django 5.1.7 on 2025-04-10 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0012_curso_duracion_curso_modalidad_diplomado_duracion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diplomado',
            name='facilitador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.facilitador'),
        ),
    ]
