# Generated by Django 5.1.7 on 2025-04-10 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0013_alter_diplomado_facilitador'),
    ]

    operations = [
        migrations.AddField(
            model_name='diplomado',
            name='publicado',
            field=models.BooleanField(default=False),
        ),
    ]
