# Generated by Django 5.1.7 on 2025-04-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0015_curso_finalizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='diplomado',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taller',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
    ]
