# Generated by Django 5.1.7 on 2025-04-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0016_diplomado_finalizado_taller_finalizado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilitador',
            name='telefono',
            field=models.BigIntegerField(),
        ),
    ]
