# Generated by Django 5.1.7 on 2025-04-16 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0017_alter_facilitador_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='restriccion_libre',
            field=models.BooleanField(default=False, help_text='Permitir que el alumno se inscriba sin restricciones'),
        ),
    ]
