# Generated by Django 5.1.7 on 2025-04-17 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0018_alumno_restriccion_libre'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
    ]
