# Generated by Django 5.1.7 on 2025-04-17 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0019_inscripcion_finalizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodo',
            name='nombre_periodo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
