# Generated by Django 5.1.7 on 2025-05-14 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0020_periodo_nombre_periodo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='grupo',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
