# Generated by Django 5.1.7 on 2025-05-14 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0022_alter_diplomado_grupo_alter_taller_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='clave',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='facilitador',
            name='clave',
            field=models.CharField(max_length=255),
        ),
    ]
