# Generated by Django 5.1.7 on 2025-05-14 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0023_alter_alumno_clave_alter_facilitador_clave'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='aula',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='dias',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='lugar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
