# Generated by Django 5.1.7 on 2025-05-14 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0024_curso_aula_curso_dias_curso_lugar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='dias',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
