# Generated by Django 5.1.7 on 2025-05-14 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0025_alter_curso_dias'),
    ]

    operations = [
        migrations.AddField(
            model_name='diplomado',
            name='aula',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='diplomado',
            name='dias',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='diplomado',
            name='lugar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='taller',
            name='aula',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='taller',
            name='dias',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='taller',
            name='lugar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
