# Generated by Django 5.1.7 on 2025-05-16 22:26

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0026_diplomado_aula_diplomado_dias_diplomado_lugar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='dias',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes')], default=list, max_length=37),
        ),
        migrations.AlterField(
            model_name='diplomado',
            name='dias',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes')], default=list, max_length=37),
        ),
        migrations.AlterField(
            model_name='taller',
            name='dias',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes')], default=list, max_length=37),
        ),
    ]
