# Generated by Django 5.1.7 on 2025-05-19 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0027_alter_curso_dias_alter_diplomado_dias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='curp',
            field=models.CharField(max_length=18, unique=True),
        ),
        migrations.AlterField(
            model_name='facilitador',
            name='curp',
            field=models.CharField(max_length=18, unique=True),
        ),
    ]
