# Generated by Django 5.1.7 on 2025-05-20 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0028_alter_alumno_curp_alter_facilitador_curp'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='token_recuperacion',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
