# Generated by Django 5.1.7 on 2025-05-20 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0029_alumno_token_recuperacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitador',
            name='token_recuperacion',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
