# Generated by Django 5.1.7 on 2025-05-30 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0031_alumno_estado_alumno_municipio_facilitador_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiplomadoLanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='diplomados_landing/')),
            ],
            options={
                'verbose_name': 'Diplomado en Landing',
                'verbose_name_plural': 'Diplomados en Landing',
                'db_table': 'diplomados_landing',
            },
        ),
    ]
