# Generated by Django 5.1.7 on 2025-05-30 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0032_diplomadolanding'),
    ]

    operations = [
        migrations.AddField(
            model_name='diplomadolanding',
            name='Modalidad',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='diplomadolanding',
            name='descripcion_modulo',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='diplomadolanding',
            name='destinatarios',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='diplomadolanding',
            name='duracion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='diplomadolanding',
            name='introduccion',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='diplomadolanding',
            name='nivel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='diplomadolanding',
            name='participantes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='diplomadolanding',
            name='particulares',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='diplomadolanding',
            name='proposito',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='diplomadolanding',
            name='recursos',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='diplomadolanding',
            name='responsable',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='diplomadolanding',
            name='titulo_modulo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='diplomadolanding',
            name='titulo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
