# Generated by Django 5.1.7 on 2025-05-30 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0033_diplomadolanding_modalidad_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diplomadolanding',
            old_name='Modalidad',
            new_name='modalidad',
        ),
    ]
