# Generated by Django 5.1.7 on 2025-05-30 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0034_rename_modalidad_diplomadolanding_modalidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diplomadolanding',
            name='descripcion_modulo',
        ),
        migrations.RemoveField(
            model_name='diplomadolanding',
            name='titulo_modulo',
        ),
        migrations.CreateModel(
            name='ModuloDiplomado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_modulo', models.CharField(max_length=200)),
                ('descripcion_modulo', models.TextField()),
                ('diplomado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='administracion.diplomadolanding')),
            ],
        ),
    ]
