# Generated by Django 5.1.7 on 2025-05-30 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0035_remove_diplomadolanding_descripcion_modulo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modulodiplomado',
            old_name='descripcion_modulo',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='modulodiplomado',
            old_name='titulo_modulo',
            new_name='titulo',
        ),
    ]
