# Generated by Django 5.1.7 on 2025-05-30 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0036_rename_descripcion_modulo_modulodiplomado_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diplomadolanding',
            name='costo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
