# Generated by Django 5.1.7 on 2025-05-31 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0037_diplomadolanding_costo'),
    ]

    operations = [
        migrations.AddField(
            model_name='diplomadolanding',
            name='programa_pdf',
            field=models.FileField(blank=True, null=True, upload_to='diplomados_landing/programas/'),
        ),
    ]
