# Generated by Django 5.1.7 on 2025-06-01 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0038_diplomadolanding_programa_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='TallerLanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=200, null=True)),
                ('descripcion_corta', models.TextField()),
                ('imagen', models.ImageField(upload_to='taller_landing/')),
            ],
            options={
                'verbose_name': 'Taller en Landing',
                'verbose_name_plural': 'Talleres en Landing',
                'db_table': 'taller_landing',
            },
        ),
    ]
