# Generated by Django 5.1.7 on 2025-06-01 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0039_tallerlanding'),
    ]

    operations = [
        migrations.AddField(
            model_name='tallerlanding',
            name='descripcion_larga',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tallerlanding',
            name='duracion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tallerlanding',
            name='responsable',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tallerlanding',
            name='subtitulo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='SesionTaller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('taller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='administracion.tallerlanding')),
            ],
        ),
    ]
