# Generated by Django 5.1.7 on 2025-06-01 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0040_tallerlanding_descripcion_larga_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tallerlanding',
            name='programa_pdf',
            field=models.FileField(blank=True, null=True, upload_to='taller_landing/programas/'),
        ),
    ]
