# Generated by Django 5.1.7 on 2025-06-01 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0041_tallerlanding_programa_pdf'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sesiontaller',
            options={'verbose_name': 'Sesión del Taller', 'verbose_name_plural': 'Sesiones del Taller'},
        ),
    ]
