# Generated by Django 5.1.7 on 2025-06-01 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0042_alter_sesiontaller_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CursoLanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=200, null=True)),
                ('descripcion_corta', models.TextField()),
                ('imagen', models.ImageField(upload_to='cursos_landing/')),
            ],
            options={
                'verbose_name': 'Cursos en Landing',
                'verbose_name_plural': 'Cursos en Landing',
                'db_table': 'cursos_landing',
            },
        ),
    ]
