# Generated by Django 5.1.7 on 2025-06-01 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0044_cursolanding_descripcion_larga_cursolanding_duracion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SesionCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='administracion.cursolanding')),
            ],
            options={
                'verbose_name': 'Sesión del Curso',
                'verbose_name_plural': 'Sesiones del Curso',
            },
        ),
    ]
