# Generated by Django 5.1.7 on 2025-06-06 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0046_noticia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('imagen', models.ImageField(upload_to='revistas/')),
                ('pdf', models.FileField(upload_to='revistas_pdfs/')),
                ('fecha_publicacion', models.DateField()),
            ],
        ),
    ]
