# Generated by Django 5.1.7 on 2025-06-18 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0047_revista'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitador',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
