# Generated by Django 5.1.7 on 2025-06-18 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0048_facilitador_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
