# Generated by Django 5.1.7 on 2025-06-18 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0049_alumno_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodo',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
